### ISSUE TITLE
sdfx_st/examples/README.md doesn't say possible values for MBED_TOOLCHAIN=<TOOLCHAIN>

### ISSUE THREAD

**Issue by pfalcon-linaro** [MCU-Driver-HAL/MCU-Driver-ST#6]
User story: As a new user, I'm trying to follow https://github.com/MCU-Driver-HAL/MCU-Driver-ST/blob/main/sdfx_st/examples/README.md . However, I get stuck at this step:

```
cmake -S . -B cmake_build -GNinja -DCMAKE_BUILD_TYPE=debug -DMBED_TOOLCHAIN=<TOOLCHAIN>
```

I have no idea what values for `<TOOLCHAIN>` are possible. (And related, which one of supposedly many alternatives I'd be recommended to use for quick start.)

**Comment by pfalcon-linaro** [comment]
(I understand this isn't really specific to MCU-Driver-ST, and would need to be repeated in every vendor implementation, so some good intro documentation perhaps should be made on MCU-Driver-HAL level. That said, as MCU-Driver-ST is the only available implementation for now, and MCU-Driver-HAL is a new project unfamiliar to users, it to would be nice to lower the learning curve for new users "now".)

**Comment by jeromecoutant** [comment]
Hi
I also tried yesterday.

For quick answer, here is what I can say:
- <TOOLCHAIN> is ARM or GCC_ARM
- for gcc, you need to have arm-none-eabi-gcc in your $PATH
- seems you also need to have ninja in your $PATH
- Jinja2 python package is as well required
-

**Comment by galak** [comment]
> Hi
> I also tried yesterday.
> 
> For quick answer, here is what I can say:
> 
>     * TOOLCHAIN is ARM or GCC_ARM
> 
>     * for gcc, you need to have arm-none-eabi-gcc in your $PATH
> 
>     * seems you also need to have ninja in your $PATH
> 
>     * Jinja2 python package is as well required

I  assume you can use `make` if you change `-GNinja`

**Comment by MarceloSalazar** [comment]
> I assume you can use make if you change -GNinja

We've checked again and added `-GNinja` as needed in Windows - see PR https://github.com/MCU-Driver-HAL/MCU-Driver-ST/pull/8

**Comment by MarceloSalazar** [comment]
I agree we need better getting started guides. This is related to https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/issues/8
