### ISSUE TITLE
sdfx_st/examples/README.md doesn't mention anything about toolchain required to build examples

### ISSUE THREAD

**Issue by pfalcon-linaro** [MCU-Driver-HAL/MCU-Driver-ST#7]
This is related to #6. https://github.com/MCU-Driver-HAL/MCU-Driver-ST/blob/main/sdfx_st/examples/README.md doesn't mention anything about toolchain(s) required to build examples, that it should be in a path, etc. Perhaps, it should mention which toolchains are supported, and recommend e.g. arm-gcc-embedded for quick start.

**Comment by MarceloSalazar** [comment]
I agree we need better getting started guides. This is related to https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/issues/8

**Comment by MarceloSalazar** [comment]
Fixed in https://github.com/MCU-Driver-HAL/MCU-Driver-ST/pull/12
